name: Test
on:
  push:
    branches:
      - "Solomon-Muhye"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Test
    concurrency: test_${{ github.head_ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Cypress E2E Tests on Storybook
        uses: cypress-io/github-action@v5
        with:
          build: pnpm build-storybook
          start: pnpm storybook
          config-file: cypress.json
          browser: chrome
          wait-on: "http://localhost:6006"

      - name: Cypress run
        run: pnpm cy:run
